stages:
  stage0:
    cmd: python convert_yaml_to_mcp_json.py --input_dir 
      /home/sagemaker-user/FunctionWrapper/description_improvement/results/StableToolBench_D1
      --output_dir /home/sagemaker-user/TOUCAN/mcp_servers
    outs:
    - ../mcp_servers
  stage1-1:
    cmd: python step1.1_gen_questions.py --num_tools 2 --sampling_strategy uniform --samples_per_server 10
    deps:
    - ../mcp_servers/
  stage1-2:
    cmd: bash step1.2_completion.sh ../data/ToolUse_smithery_49350_2tool_1762908421/ToolUse_s2q_smithery_49350_2tool_1762908421_prepared.jsonl gpt-41-2025-04-14 openai
  stage1-3:
    cmd: python step1.3_process_completion.py --input_file 
      ../data/ToolUse_smithery_10239_1tool_1762851360/ToolUse_s2q_smithery_10239_1tool_1762851360_gpt-41-2025-04-14_results.jsonl
  convert2query:
    cmd: python convert_preview_to_g1.py --preview_file 
      ../data/ToolUse_smithery_10239_1tool_1762851360/processed/ToolUse_s2q_smithery_10239_1tool_1762851360_gpt-41-2025-04-14_3sanitized.jsonl
      --tools_root_dir 
      /home/sagemaker-user/FunctionWrapper/StableToolBench/data/toolenv/tools 
      --output ../data/generated.json
